name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:

      redis:
        image: redis
#        options: >-
#          --health-cmd "redis-cli ping"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
        ports:
          - 6379:6379

      memcached:
        image: memcached
        ports:
          - 11211:11211

    steps:
    - uses: actions/checkout@v2

    - name: Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y apache2-dev libcjose-dev libssl-dev check pkg-config
        sudo apt-get install -y libjansson-dev libcurl4-openssl-dev libhiredis-dev

    - name: Configure
      run: |
        ./autogen.sh
        ./configure

    - name: Make
      run: make

    - name: Test
      run: make check
